#!/usr/bin/env bash
echo '#!/usr/bin/env bash'

eval "$(printf 'source "%s"\n' "$@")"

declare | sed -n -e "/^_=/,\$p" | sed -n -e "1d;p"

printf '
# run `clc` if not being sorced
# https://stackoverflow.com/a/2684300
[[ "${BASH_SOURCE[0]}" = "${0}" ]] && clc "${@}"
'
