#!/usr/bin/env bash
echo '#!/usr/bin/env bash'

eval "$(printf 'source "%s"\n' "$@")"

declare -f  # print the imported functions

printf '
# run `clc` if not being sorced
# https://stackoverflow.com/a/2684300
if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
  clc "${@}"
fi
'
